#!/bin/bash -ex

LIBVIRT_USER=libvirt-qemu
PASSWORD=qwe123

INSTANCE=maas
PROFILE=root

BRIDGE=$(aoi-get-libvirt-bridge default)
BRIDGE_IP=$(ip addr show dev $BRIDGE | grep '^    inet' | awk '{print $2}' | cut -d '/' -f 1)


if ! id libvirt-qemu | awk '{ print $3 }' | grep '(libvirtd)' | grep -q '(kvm)'; then
    echo "Adding $LIBVIRT_USER to the libvirtd group, and setting password..."
    sudo usermod -a -G libvirtd,kvm -s /bin/bash $LIBVIRT_USER
    echo "$LIBVIRT_USER:$PASSWORD" | sudo chpasswd
fi

echo "libvirt should now be available remotely."
echo "URL: qemu+ssh://$LIBVIRT_USER@$BRIDGE_IP/system"
echo "Password: $PASSWORD"

# These might already be created, so we won't worry if it fails.
aoi-create-testhost pxe1 || true
aoi-create-testhost pxe2 || true
aoi-create-testhost pxe-bond1 || true
aoi-create-testhost pxe-bond2 || true

aoi-ssh $INSTANCE maas $PROFILE machines add-chassis chassis_type=virsh hostname=qemu+ssh://libvirt-qemu@$BRIDGE_IP/system password=$PASSWORD prefix_filter=pxe
echo ""
